### ISSUE TITLE
段哥，给你发了一封邮件，有几个问题需要咨询你一下，请查阅一下！

### ISSUE THREAD

**Issue by sych520** [duanhai/Tun2socks-mobile-demo#9]

**Comment by duanhai** [comment]
Sorry,最近没有登录没有看到，暂没有收到你的邮件。duanhai@outlook.com

**Comment by sych520** [comment]
其实就是15m内存问题 不知道这个要如何处理呢




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 13:54，Tony 写道：

Sorry,最近没有登录没有看到，暂没有收到你的邮件。duanhai@outlook.com

**Comment by duanhai** [comment]
这个问题应该是 v2ray core里面的连接数引起的，这个需要有点golang基础才好去读源码并且修改，我只是弄着玩了下，没有深入下去。搜索之前的v2ray core有人提过很多issue，跟着线索可以去尝试下。
________________________________
发件人: wfkbyni <notifications@github.com>
发送时间: 2019年11月11日 13:56
收件人: duanhai/Tun2socks-PacketTunnelDemo <Tun2socks-PacketTunnelDemo@noreply.github.com>
抄送: Tony <duanhai@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [duanhai/Tun2socks-PacketTunnelDemo] 段哥，给你发了一封邮件，有几个问题需要咨询你一下，请查阅一下！ (#9)

其实就是15m内存问题 不知道这个要如何处理呢




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 13:54，Tony 写道：

Sorry,最近没有登录没有看到，暂没有收到你的邮件。duanhai@outlook.com

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
